### ISSUE TITLE
Автозапуск скрипта 

### ISSUE THREAD

**Issue by alexinario** [Cherkes001/raspberrypi_hardwaremonitor#2]
Если делали по инструкции, то скрипт окажется в данной директории, далее прописываете данные команды:
```
sudo cp -i /home/pi/raspberrypi_hardwaremonitor/hardware_monitor.py /bin
sudo crontab -e
```
Добавить в crontab: 
`@reboot python /bin/hardware_monitor.py &`

**Comment by teuchezh** [comment]
> Если делали по инструкции, то скрипт окажется в данной директории, далее прописываете данные команды:
> 
> ```
> sudo cp -i /home/pi/raspberrypi_hardwaremonitor/hardware_monitor.py /bin
> sudo crontab -e
> ```
> 
> Добавить в crontab:
> `@reboot python /bin/hardware_monitor.py &`

В планах было сделать баш скрипт, который автоматически прописывал бы автостарт, и вероятнее всего это был бы сервис. Но Вы знаете как это бывает, пилишь, пилишь и хоба пропадает интерес.
Добавлю в Readme, только сейчас увидел это. Спасибо
